name: Code Integration

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Step 4: Super Lint
      - name: Lint code
        run: |
          yarn eslint "src/**/*.{ts,tsx,js,jsx}" --max-warnings=0
          yarn prettier --check "src/**/*.{ts,tsx,js,jsx,json,css,scss,md}"

      # Step 5: Run tests
      - name: Run tests
        run: yarn test

      # Step 6: Build the project
      - name: Build project
        run: yarn build
